#!/bin/bash
# render-dnsmasq.sh — generate + terapkan konfigurasi DHCP/DNS dinamis
#   * pool DHCP (dhcp-range, option gateway/dns) dari tabel pools
#   * static lease per-pelanggan (dhcp-host = MAC -> IP statis)
# File target: /etc/dnsmasq.d/router-managed.conf (reload dnsmasq).
# Idempotent: file ditulis ulang penuh; konfig base /etc/dnsmasq.d/router.conf
# (DNS + VLAN lab) TIDAK disentuh.
set -euo pipefail

APP="${APP_DIR:-/opt/ubuntu-router}"
STATE="$APP/state"
GEN="$STATE/gen"
DB="$STATE/router.db"
OUT="$GEN/router-managed.conf"
DST="/etc/dnsmasq.d/router-managed.conf"

command -v sqlite3 >/dev/null || { echo "ERROR: sqlite3 tidak ada"; exit 1; }
mkdir -p "$GEN"

{
    echo '# generated by ubuntu-router render-dnsmasq.sh — jangan edit manual'
    # ---------- pool DHCP ----------
    sqlite3 -separator $'\t' "$DB" \
      "SELECT name, iface, subnet, start_ip, end_ip, router_ip, dns1, dns2, leasetime
       FROM pools WHERE active=1 ORDER BY id;" 2>/dev/null \
    | while IFS=$'\t' read -r name iface subnet start end gw dns1 dns2 lease; do
        [ -n "$start" ] || continue
        [ -n "$subnet" ] || subnet="255.255.255.0"
        [ -n "$lease" ]  || lease="12h"
        echo "dhcp-range=tag:$name,$start,$end,$subnet,$lease"
        [ -n "$gw" ]   && echo "dhcp-option=tag:$name,3,$gw"
        if [ -n "$dns1" ]; then
            echo "dhcp-option=tag:$name,6,$dns1${dns2:+,$dns2}"
        fi
        echo "dhcp-option=tag:$name,1,$subnet"
    done

    # ---------- static lease per pelanggan ----------
    sqlite3 -separator '|' "$DB" \
      "SELECT lower(c.mac), c.static_ip, c.name
       FROM customers c WHERE c.active=1 AND c.type='dhcp'
         AND c.mac != '' AND c.static_ip IS NOT NULL AND c.static_ip != ''
       ORDER BY c.id;" 2>/dev/null \
    | while IFS='|' read -r mac ip host; do
        # normalisasi ke format xx:xx:xx:xx:xx:xx (dnsmasq dhcp-host)
        norm=$(echo "$mac" | sed 's/\(..\)/\1:/g;s/:$//')
        echo "dhcp-host=$norm,$ip,$host"
    done

    } > "$OUT"

if [ -w "$(dirname "$DST")" ]; then
    cp -f "$OUT" "$DST"
    if systemctl reload dnsmasq 2>/dev/null; then
        echo "OK: dnsmasq reload ($DST)"
    else
        echo "OK: file diterapkan; dnsmasq reload dilewati"
    fi
else
    echo "OK: tidak punya akses ke /etc/dnsmasq.d (skip deploy), file: $OUT"
fi